# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "monthly"

  # Maintain dependencies for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "skip-changelog"
    schedule:
      interval: "monthly"
